### ISSUE TITLE
Icons for Nodes

### ISSUE THREAD

**Issue by Sythelux** [asmaloney/GDExtensionTemplate#58]
I'm a bit lost, where to ask for this.

Is it possible to set an Icon for a GDExtension class (e.g. ExampleMin in this repo) to show up in the "create new node" dialog.

**Comment by asmaloney** [comment]
> I'm a bit lost, where to ask for this.

Yes, it can be tough to figure out where to go for help since the community is fragmented among several platforms. And some platforms which are active, like discord, are not preserved/searchable like a forum would be so solutions are lost. Anyway...

My project is more about the build process for extensions rather than implementing the extensions themselves, however I found [an issue on godot-cpp](https://github.com/godotengine/godot/pull/75472) which looks like it added this capability a while ago.

I didn't read through the whole thing to figure out how to do it though 😄

**Comment by Sythelux** [comment]
It looks like the way to go is to add this to the gdextension file (but with ones own class)

```
[icons]
Threen = "res://bin/icon_tween.svg"
```

I'll try that. Thank you for the help. You could probably add it for one of the Example classes. I often come back to this repo to see how you achieved some things ^^'' and I agree we would need a non-discord forum. I might open a GDExtension Lemmy for it. :p

**Comment by asmaloney** [comment]
Ah, yeah. It is _configure-y_, so maybe it makes sense to add it here.

I'll reopen this issue so I remember to take a look next time I work on this project.

Thanks!
